global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "Prometheus Server"
    scrape_interval: 5s
    static_configs:
      - targets: ["poc-observability.com:9090"] # Prometheus Server
  - job_name: "Loki server"
    scrape_interval: 5s
    static_configs:
      - targets: ["poc-observability.com:3100"] # Loki Server
  - job_name: "golang app"
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["poc-observability.com:8080"] # Golang app

